---
- name: build the VM if not present
  hosts: homelab.kam.example.com
  gather_facts: false
  become: true
  tasks:
    - name: creating VM for the lab on x86
      vars:
       vm_name: "{{ item }}" 
      include_role:
       name: create_vms
      loop:
        - eda_controller 
        - exec_node 
        - managed_node 
