---
- name: Restore Dell OS10 Configuration
  hosts: all
  gather_facts: false

  vars:
    config_file_path: "sample_playbooks/configs/{{ inventory_hostname }}.cfg"
  #connection: network_cli
  #collections:
  #  - dellemc.os10

  tasks:
    - name: get the current dir
      command: pwd
      register: the_curr_dir

    - name: show the pwd
      debug:
        var: the_curr_dir
        
    - name: get the content of a cfg
      set_fact:
        config_content: "{{ lookup('file', config_file_path) }}"
      #command: cat "{{ config_file_path }}"
      #command: cat "{{ inventory_hostname }}"
      #copy:
      #  src: "{{ config_file_path }}"
      #  dest: /tmp/
      register: config_restore_result

    - name: Display config restore result
      debug:
        var: config_content
