---
- name: Restore Dell OS10 Configuration
  hosts: all
  gather_facts: false

  vars:
    config_file_path: "sample_playbooks/configs/{{ inventory_hostname }}.cfg"
    test_str: "This is a test"
  #connection: network_cli
  #collections:
  #  - dellemc.os10

  tasks:
    - name: get the content of a cfg
      set_fact:
        config_content: "{{ lookup('file', config_file_path) }}"
      #command: cat "{{ config_file_path }}"
      #command: cat "{{ inventory_hostname }}"
      #copy:
      #  src: "{{ config_file_path }}"
      #  dest: /tmp/
      register: config_restore

    - name: set fact to compare
      set_fact:
        config_to_comp: "This is running config"
      register: config_running

    - name: Display config restore result
      debug:
        #var: config_content
        var: config_restore
      register: config_restore_result

    - name: Display compare
      debug:
        var: test_str
      when: config_restore_result.config_restore.ansible_facts.config_content != config_running.ansible_facts.config_to_comp



