---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - name: "test name"
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: "Trigger Playbook with payload"
      #condition: event.payload != ""
      condition: event.payload != null
      action:
        run_job_template:
          #name: DemoJobTemplate
          #organization: Default
          name: "DemoEDAHello Cust"
          #name: custmain dev CasC Ctrl CD Webhook Trigger
          #organization: custmain
          organization: "Test with space"
          var_root: "{{ event.payload.repository.project }}"
          job_args:
            extra_vars:
              json_payload: "{{ event.payload.repository.project.name }}"
              message: "from EDA"
