---
- name: Listen for events on a webhook
  hosts: all
  ## Define our source for events
  sources:
    - name: "test name"
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Trigger Playbook with payload
      condition: event.payload != ""
      action:
        run_job_template:
          #name: DemoJobTemplate
          #organization: Default
          name: DemoEDAHello
          #name: custmain dev CasC Ctrl CD Webhook Trigger
          organization: custmain
          job_args:
            extra_vars:
              json_payload: "{{ event.payload.repository.project.name }}"
              message: FromEDA
