---
- name: restart the site
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - debug:
        msg: "fixing the webserver"
      when: ansible_facts['nodename'] == 'webserver'

    - name: restart the container
      shell:
        cmd: podman start 444b8caa8626
      when: ansible_facts['ansible_hostname'] == 'webserver'

