---
- name: restart the site
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "fixing the webserver"
      when: ansible_facts['nodename'] == 'webserver'

    - name: restart the container
      containers.podman.podman_container:
        name: flamboyant_morse
        state: started
      when: ansible_facts['nodename'] == 'webserver'

