---
- name: restart the site
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - debug:
        msg: "fixing the webserver"
      when: ansible_facts['inventory_hostname'] == 'webserver'

    - name: restart the container
      shell:
        cmd: podman start 444b8caa8626
      when: ansible_facts['inventory_hostname'] == 'webserver'

