---
- name: restart the site
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - debug:
        msg: "fixing the webserver"
        #var: inventory_hostname

    - name: restart the container
      shell:
        cmd: podman start 444b8caa8626
      #when: inventory_hostname == 'webserver'

