---
- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:   
    - ansible.eda.kafka:
        host: 10.0.0.73
        port: 9092
        topic: eda-test-events
        group_id:

  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      #condition: event.message == "Ansible is cool"
      condition: event.body.message == "Ansible is cool"
      ## Define the action we should take should the condition be met
      action:
        run_job_template:
          name: say-what.yml

